config/routes.rb
Rails.application.routes.draw do
  
  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  get 'welcome/index'

  get 'about' => 'welcome#about'

  get 'welcome' => 'welcome#index'

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :require_sign_in
	before_action :authorize_user, only: [:destroy]

	def create
		@post = Post.find(params[:post_id])
		comment = @post.comments.build(comment_params)
		comment.user = current_user

		if comment.save
			flash[:notice] = "Comment saved successfully."
			redirect_to topic_post_path(@post.topic_id, @post.id)
		else
			flash[:alert] = "Comment failed to save."
			redirect_to topic_post_path(@post.topic_id, @post.id)
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		comment = @post.comments.find(params[:id])
		if comment.destroy
			flash[:notice] = "Comment was deleted."
			redirect_to topic_post_path(@post.topic_id, @post.id)
		else
			flash[:alert] = "Comment could't be deleted. Try again."
			redirect_to topic_post_path(@post.topic_id, @post.id)
		end
	end

	private

		def comment_params
			params.require(:comment).permit(:body)
		end

		def authorize_user
			comment = Comment.find(params[:id])
			unless current_user == comment.user || current_user.admin?
				flash[:alert] = "You do not have permission to delete comment."
				redirect_to topic_post_path(comment.post.topic_id, comment.post.id)
			end
		end
end

app/helpers/comments_helper.rb
module CommentsHelper
	def user_is_authorized_for_comments?(comment)
		current_user && (current_user == comment.user || current_user.admin?)
	end
end

app/views/comments/_comment.html.erb
<div class="media">
	<div class="media-body">
		<small>
			<%= comment.user.name %> commented <%= time_ago_in_words(comment.created_at) %> ago
			<% if user_is_authorized_for_comments?(comment) %>
				<%= link_to "Delete", post_comment_path(comment.post_id, comment.id), method: :delete %>
 			<% end %>
		</small>
		<p><%= comment.body %></p>
	</div>
</div>

app/views/comments/_form.html.erb
<h4>Add a comment</h4>

<%= form_for [post, comment] do |f| %>
	<div class="form-group">
		<%= f.label :body, class: 'sr-only' %>
		<%= f.text_area :body, class: 'form-control', placeholder: "Enter your comment" %>
	</div>
	<div class="form-group">
		<%= f.submit "Submit Comment", class: 'btn btn-default pull-right' %>
	</div>
<% end %>