config/routes.rb
Rails.application.routes.draw do
  
  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  get 'welcome/index'

  get 'about' => 'welcome#about'

  get 'welcome' => 'welcome#index'

  root 'welcome#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :posts, dependent: :destroy

	validates :name, length: { minimum: 5 }, presence: true
	validates :description, length: { minimum: 15 }, presence: true
	
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	before_action :require_sign_in, except: [:index, :show]
	before_action :authorize_user, except: [:index, :show]

	def index
		@topics = Topic.all
	end

	def show
		@topic = Topic.find(params[:id])
	end

	def new
		@topic = Topic.new
	end

	def create
		@topic = Topic.new(topic_params)

		if @topic.save
			flash[:notice] = "New Topic successfully created!"
			redirect_to topic_path(@topic.id)
		else
			flash.now[:alert] = "Topic wasn't saved correctly. Please try again."
			render :new
			end
	end

	def edit
		@topic = Topic.find(params[:id])
	end

	def update
		@topic = Topic.find(params[:id])
		@topic.assign_attributes(topic_params)

		if @topic.save
			flash[:notice] = "Topic updated successfully"
			redirect_to topic_path(@topic.id)
		else
			flash.now[:alert] = "Topic wasn't updated. Please try again."
			render :edit
		end
	end

	def destroy
		@topic = Topic.find(params[:id])

		if @topic.destroy
			flash[:notice] = "Topic was successfully deleted!"
			redirect_to action: :index # possibile topics_path
		else
			flash.now[:alert] = "Topic wasn't deleted"
			render :show
		end
	end

	private

		def topic_params
			params.require(:topic).permit(:name, :description, :public)
		end

		def authorize_user
			unless current_user.admin? || current_user.moderator?
				flash[:alert] = "You must be admin to do that."
				redirect_to topics_path
			end
		end
end

app/helpers/topics_helper.rb
module TopicsHelper
	def user_is_authorized_for_topics?
		current_user && current_user.admin?
	end

	def user_is_moderator?
		current_user && current_user.moderator?
	end
end

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>
	<% if topic.errors.any? %>
		<div class="alert alert-danger">
			<h4><%= pluralize(topic.errors.count, "error") %></h4>
			<ul>
				<% topic.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= form_group_tag(topic.errors[:name]) do %>
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control', placeholder: "Enter the name for this topic" %>
	<% end %>
	<%= form_group_tag(topic.errors[:description]) do %>
		<%= f.label :description %>
		<%= f.text_area :description, class: 'form-control', placeholder: "Enter the description for this topic" %>
	<% end %>
	<div class="form-group">
		<%= f.label :public, class: 'checkbox' do %>
			<%= f.check_box :public %> Public Topic
		<% end %>
	</div>
	<div class="form-group">
		<%= f.submit "Save", class: 'btn btn-success' %>
	</div>
<% end %>

app/views/topics/_topic.html.erb
<div class="media">
	<div class="media-body">
		<h4 class="media-heading">
			<%= link_to topic.name, topic_path(topic.id) %>
		</h4>
		<small>
			<%= topic.description %>
		</small>
	</div>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
	<div class="col-md-4">
		<p>Guidelines to edit post</p>
		<ul>
			<li>bla bla bla bla</li>
			<li>bla bla bla bla</li>
			<li>bla bla bla bla</li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= render partial: 'form', locals: { topic: @topic } %>
	</div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
	<div class="col-md-8">
		<%= render @topics %>
	</div>
	<% if user_is_authorized_for_topics? %>
		<div class="col-md-4">
			<%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
		</div>
	<% end %>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
	<div class="col-md-4">
		<p>Giudelines for topics:</p>
		<ul>
			<li>bla bla bla bla</li>
			<li>bla bla bla bla</li>
			<li>bla bla bla bla</li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= render partial: 'form', locals: { topic: @topic } %>
	</div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if user_is_authorized_for_topics? %>
	<%= link_to "Edit Topic", edit_topic_path(@topic.id), class: 'btn btn-success' %>
	<%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete this topic and all posts linked to it?"} %>
<% end %>
<div class ="row">
	<div class="col-md-8">
		<p class="lead"><%= @topic.description %></p>
		<%= render @topic.posts %>
	</div>
	<div class="col-md-4">
		<% if current_user %>
			<%= link_to "New Post", new_topic_post_path(@topic.id), class: 'btn btn-success' %>
		<% end %>
	</div>
</div>