config/routes.rb
Rails.application.routes.draw do
  
  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  get 'welcome/index'

  get 'about' => 'welcome#about'

  get 'welcome' => 'welcome#index'

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
	has_many :comments, dependent: :destroy

	validates :title, length: { minimum: 5 }, presence: true
	validates :body, length: { minimum: 20 }, presence: true
	validates :topic, presence: true
	validates :user, presence: true

	default_scope { order('created_at DESC') }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :require_sign_in, except: :show
  before_action :authorize_user, except: [:show, :new, :create]

  def show
  	@post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
  	@post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    @post.user = current_user
  	
    if @post.save
  		flash[:notice] = "Post was saved."
  		redirect_to topic_post_path(@topic.id, @post.id)
  	else
  		flash.now[:alert] = "There was an error saving the post. Please try again."
  		render :new
  	end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)
    
    if @post.save
      flash[:notice] = "Post was successfully updated!"
      redirect_to topic_post_path(@post.topic_id, @post.id)
    else
      flash.now[:alert] = "Something went wrong. Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted!"
      redirect_to topic_path(@post.topic_id)
    else
      flash.now[:alert] = "Sorry, the post wasn't deleted."
      render :show
    end
  end

  private
  
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def authorize_user
      post = Post.find(params[:id])

      unless current_user == post.user || current_user.admin? || current_user.moderator?
        flash[:alert] = "You must be an admin to do that"
        redirect_to topic_post_path(post.topic_id, post.id)
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
	def user_is_authorized_for_posts(post)
		current_user && ( current_user == post.user || current_user.admin? )
	end

	def user_is_moderator?
		current_user &&  current_user.moderator?
	end
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
	<% if post.errors.any? %>
		<div class="alert alert-danger">
			<h4><%= pluralize(post.errors.count, "error") %></h4>
			<ul>
				<% post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= form_group_tag(post.errors[:title]) do %>
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control', placeholder: "Enter the post title" %>
	<% end %>
	<%= form_group_tag(post.errors[:body]) do %>
		<%= f.label :body %>
		<%= f.text_area :body, rows: 8, class: 'form-control', placehoder: "Enter the post" %>
	<% end %>
	<div class="form-group">
		<%= f.submit "save", class: 'btn btn-success' %>
	</div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
	<div class="media-body">
		<h4 class="media-heading">
			<%= link_to post.title, topic_post_path(@topic.id, post.id) %>
		</h4>
		<small>
			submitted <%= time_ago_in_words(post.created_at) %> ago
			by <%= post.user.name %>
			<br />
			<%= post.comments.count %> comments
		</small>
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
	<div class="col-md-4">
		<p>Guidelines to edit post</p>
		<ul>
			<li>bla bla bla bla</li>
			<li>bla bla bla bla</li>
			<li>bla bla bla bla</li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
	</div>
</div>

app/views/posts/new.html.erb
<h1>New Post for topic "<i><%= @topic.name %></i>"</h1>

<div class="row">
	<div class="col-md-4">
		<p>Guidelines for posts</p>
		<ul>
			<li>Make sure it rhymes.</li>
			<li>Don't use the letter "A".</li>
			<li>The incessant use of hashtags will get you banned.</li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= render partial: 'form', locals: { topic: @topic, post: @post } %>
	</div>
</div>

app/views/posts/show.html.erb
<h1>
	<%= @post.title %>
	<small>
		submitted <%= time_ago_in_words(@post.created_at) %> by <%= @post.user.name %>
	</small>
</h1>

<div class="col-md-8">
	<p><%= @post.body %></p>
	<div>
		<h3>Comments</h3>
		<%= render @post.comments %>
	</div>
	<% if current_user %>
		<%= render 'comments/form', comment: Comment.new, post: @post %>
	<% end %>
</div>
<div class="col-md-4">
	<% if user_is_authorized_for_posts(@post) %>
		<%= link_to "Edit", edit_topic_post_path(@post.topic_id, @post.id), class: 'btn btn-success' %>
		<%= link_to "Delete!", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
	<% end %>
</div>